version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'sap'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/SAP-service
    ports:
      - "8000:8000"
    depends_on:
      - db
    expose: 
        - "8000"